### ISSUE TITLE
Returning superclasses in treats responses

### ISSUE THREAD

**Issue by cbizon** [broadinstitute/molecular-data-provider#308]
For this query:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n00",
          "predicates": [
            "biolink:treats"
          ],
          "object": "n01"
        }
      },
      "nodes": {
        "n00": {
          
          "categories": [
            "biolink:SmallMolecule"
          ]
        },
        "n01": {
          "ids": [
            "MONDO:0009242"
          ],
          "categories": [
            "biolink:Disease"
          ]
        }
      }
    }
  }
}
```

I am getting back treats edges for superclasses of MONDO:0009242.

These are the id's and names being bound to n01 in the response:

MONDO:0000839 OBSOLETE TERM 4
MONDO:0002254 syndromic disease 2
MONDO:0020066 Ehlers-Danlos syndrome 2
MONDO:0003900 connective tissue disorder 12
MONDO:0005328 eye disorder 77
MONDO:0003847 Mendelian disease 1
MONDO:0005093 skin disorder 153

None of these are valid responses, and their breadth causes all sorts of problems for us downstream.

**Comment by vdancik** [comment]
MolePro obtained these from Automat (https://automat.transltr.io/ontological-hierarchy/1.3/query) using the following query:

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": [
                        "biolink:subclass_of"
                    ]
                }
            },
            "nodes": {
                "n00": {
                    "ids": [
                        "MONDO:0000839"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                },
                "n01": {
                    "ids": [
                        "MONDO:0009242"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            }
        }
    }
}
```

**Comment by cbizon** [comment]
Mentioned this on slack, but for posterity here are a couple of points:

We'll fix the logic in automat, but in the meantime, I think that the results are correct if you only use the results where the qnode_id = id in the node bindings.

Also, the next version of automat that is moving into ci / test no longer has ontological-hierarchy.   But you can get the same information from ubergraph, e.g. https://automat.renci.org/ubergraph/1.4

**Comment by EvanDietzMorris** [comment]
The subclass issues were fixed on the automat side in dev now (https://automat.renci.org/) and will be pushed to test next week if it's working well.

Note that the "ontological-hierarchy" KG was a subset of Ubergraph and has been removed from Automat in current deployments. Ubergraph Non-redundant (formerly called Uberongraph) is a subset of Ubergraph with many logically redundant edges pruned. Going forward Ubergraph is probably the best source for subclass/superclass queries.

**Comment by vdancik** [comment]
Fixed in MolePro as well.
