### ISSUE TITLE
Invalid CURIE Identifiers Being Returned in Nodes

### ISSUE THREAD

**Issue by MarkDWilliams** [broadinstitute/molecular-data-provider#311]
WTISQLWAPBSCSF-UHFFFAOYSA-N comes back as a node ID from MolePro for this query, when TRAPI mandates that node IDs be CURIE.
`"data": {
      "message": {
        "query_graph": {
          "nodes": {
            "n0": {
              "ids": [
                "MONDO:0001754"
              ],
              "categories": [
                "biolink:Disease"
              ]
            },
            "n1": {
              "categories": [
                "biolink:ChemicalEntity"
              ]
            }
          },
          "edges": {
            "e0": {
              "subject": "n1",
              "object": "n0",
              "predicates": [
                "biolink:ameliorates",
                "biolink:treats",
                "biolink:prevents",
                "biolink:affects"
              ]
            }
          }
        }
      }
    }`

**Comment by vdancik** [comment]
All node ids are now CURIEs.
